---
# Create pgadmin4 container
- name: "Create and start pgadmin4 container"
  docker_container:
    name: "{{ pgadmin_container_name }}"
    image: "{{ pgadmin_image_name }}"
    state: "started"
    env:
      PGADMIN_DEFAULT_EMAIL: "{{ postgres_user }}"
      PGADMIN_DEFAULT_PASSWORD: "{{ postgres_password }}"
      PGADMIN_LISTEN_PORT: "{{ pgadmin_listen_port }}"
      # PGADMIN_SERVER_JSON_FILE: "/pgadmin4/servers.json"
    ports:
      - "{{ pgadmin_port }}:{{ pgadmin_listen_port }}"
    volumes:
      - "pgadmin4Data:/var/lib/pgadmin"
