---
- name: Template du docker compose
  template:
    src: "servers.json.j2"
    dest: "/home/{{ ansible_user }}/servers.json"

- name: Template du docker compose
  template:
    src: "docker-compose.yml.j2"
    dest: "/home/{{ ansible_user }}/docker-compose.yml"

- name: "docker compose pgadmin4 up -d"
  command: "docker-compose up -d"
  args:
    chdir: "/home/{{ ansible_user }}"