---
# handlers file for pgadmin4_role
- name: "Reload systemd"
  systemd:
    daemon_reload: "yes"
  become: true

- name: "Restart docker"
  systemd:
    name: "docker"
    state: "restarted"
  become: true
